# Generated by Django 3.0.8 on 2020-10-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='사용자 이름')),
                ('user_id', models.CharField(max_length=32, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('user_re_pw', models.CharField(max_length=128, verbose_name='비밀번호 확인')),
            ],
        ),
    ]
